# -*- coding: utf-8 -*-
"""yolo10_part2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DNnF3k6WXFMD5qAD32ca8FxAnA13Tbcm
"""

! gdown '1twdtZEfcw4ghSZIiPDypJurZnNXzMO7R'

!mkdir safety_helmet_dataset
!unzip -q '/content/Safety_Helmet_Dataset.zip' -d '/content/safety_helmet_dataset'

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/THU-MIG/yolov10.git
# %cd yolov10
!pip install -q -r requirements.txt
!pip install -e .

!wget https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10n.pt

from ultralytics import YOLOv10

MODEL_PATH = 'yolov10n.pt'
model = YOLOv10(MODEL_PATH)

YAML_PATH = '../safety_helmet_dataset/data.yaml'
EPOCHS = 20
IMG_SIZE = 320
BATCH_SIZE = 256

model.train(data = YAML_PATH,epochs = EPOCHS ,batch = BATCH_SIZE , imgsz = IMG_SIZE)

TRAINED_MODEL_PATH = 'runs / detect/train/weights/best.pt'
model = YOLOv10(TRAINED_MODEL_PATH)

model.val(data = YAML_PATH, imgsz = IMG_SIZE, split ='test')